### ISSUE TITLE
--Closed---

### ISSUE THREAD

**Issue by RoyIL** [CodeShark-Dev/NoFuserEx#10]

**Comment by fr34kyn01535** [comment]
At some points my friend Baiz it's just simpler to write the software yourself then trying to steal it from others :)  Requesting a close because OP is obviously trying to break obfuscation on my software - violating my terms and hurting my copyright.

**Comment by RoyIL** [comment]
*obfuscation
@fr34kyn01535 
huh, there is only 1 problem. 
as I know your shit is licensed for resale , did I broke it?
anyway, How you get here?

**Comment by fr34kyn01535** [comment]
Nope its not licensed for resale. Yes you brake it if you intend to.

**Comment by RoyIL** [comment]
@fr34kyn01535 How So?
