### ISSUE TITLE
Wont Work

### ISSUE THREAD

**Issue by RoyIL** [CodeShark-Dev/NoFuserEx#4]
i try to use your program and wont clean the .dll

**Comment by RoyIL** [comment]
This Writing Like this clean the file but when i try to decompile him still the Confused Code

**Comment by ghost** [comment]
this is because it doesnt remove the control flow 
so yes everything else has been removed (near enough)

**Comment by RoyIL** [comment]
What should i do to fix it

**Comment by undebel** [comment]
Can you show me your error or send me the file for see it?

**Comment by RoyIL** [comment]
Try this : http://www.filedropper.com/vaultplugin
