### ISSUE TITLE
Another Bug

### ISSUE THREAD

**Issue by RoyIL** [CodeShark-Dev/NoFuserEx#5]
The No.1 Bug was that the program wont clear and the other bug is on the old version i have error : "File Is Not a .net portable executable. Skipping... 

please help me

**Comment by ghost** [comment]
is the dll defiantly .net?
can it be loaded properly

**Comment by RoyIL** [comment]
I Using This For My GameServer. 
and the server Load The Plugin. 
Also I was Trying to use .dll on this version and on the old one And the old work and ur wont work

**Comment by undebel** [comment]
Maybe your file is corrupted.

**Comment by RoyIL** [comment]
No . the files is not corrupted.
I try like 3 files or more....

**Comment by undebel** [comment]
Can you send me the file?

**Comment by RoyIL** [comment]
Try This : http://www.filedropper.com/vaultplugin

**Comment by undebel** [comment]
NoFuserEx works perfectly, just need to remove the control flow after use NoFuserEx.

**Comment by RoyIL** [comment]
How to remove the control flow xd?

**Comment by Arrowsurf** [comment]
Yeah how does one do that?
